version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MPuzo1920
      POSTGRES_DB: o2_db
    volumes:
      - dbdata:/var/lib/postgresql/data


  o2:
    image: stgolovin/o2
    ports:
      - "8000:8000"
    depends_on:
      - db

 


volumes:
  dbdata: